---
title: "Project_Data_Graphing"
author: "Duncan Ferguson"
date: "5/31/2021"
output: html_document
---

# Library Imports
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggplot2)
library(dplyr)
library(lubridate)
library(scales)
library(repr)
library(readr)
library(caret)
```

# Importing Data
```{r}
dat <-read.csv("Lake_Powell_Data.csv")
dat
```
# Changing Date Formats
```{r}
strDates <- dat$datetime
dat$datetime <- as.Date(strDates, "%m/%d/%Y")
dat

```

# Simple Graph of Lake Powell Pool Elevation

```{r}

#Setting Time Frame
min <- as.Date("1964-01-01")
max <- NA

dat %>%
  ggplot(aes(x=datetime, y=pool.elevation))+
    ggtitle("Lake Powell Pool Elevation")+
    geom_line(aes(y=pool.elevation , color="Current Pool Elevation"))+
    geom_hline(aes(yintercept=3490, color="Power Loss Elevation"))+
    geom_smooth(method = "lm", se =FALSE)+
    labs(x ="Year", y="Pool Elevation", color="Legend")+scale_x_date(limits = c(min,max))
    
```

```{r}

#Setting Time Frame
min <- as.Date("1980-01-01")
max <- NA

dat %>%
  ggplot(aes(x=datetime, y=pool.elevation))+
    ggtitle("Lake Powell Pool Elevation after 1980")+
    geom_line(aes(y=pool.elevation , color="Current Pool Elevation"))+
    geom_hline(aes(yintercept=3490, color="Power Loss Elevation"))+
    geom_smooth(method = "lm", se =FALSE)+
    labs(x ="Year", y="Pool Elevation", color="Legend")+scale_x_date(limits = c(min,max))
```



# Filtering Dat Time
```{r}
dat %>% filter(dat$datetime >= as.Date("1980-01-01"))
```
# Graphing Inflows by Month
```{r}
plot_Inflows_By_Month <- ggplot(data=dat %>% filter(dat$datetime >= as.Date("1980-01-01")),
                                aes(month(datetime, label=TRUE, abbr=TRUE),
                                total.inflows, group=factor(year(datetime)), colour=factor(year(datetime))))+
                                geom_smooth()+
                                theme_classic()+
                                labs(x="Month", colour="Year")+
                                ggtitle("Total Inflows")
plot_Inflows_By_Month
```
```{r}
plot_Outflows <- ggplot(data=dat %>% filter(dat$datetime >= as.Date("1980-01-01")),
                                aes(month(datetime, label=TRUE, abbr=TRUE),
                                total.release, group=factor(year(datetime)), colour=factor(year(datetime))))+
                                geom_smooth()+
                                theme_classic()+
                                labs(x="Month", colour="Year")+
                                ggtitle("Total Release")
plot_Outflows
```

# Power Release
```{r}
plot_power_release <- ggplot(data=dat %>% filter(dat$datetime >= as.Date("1980-01-01")),
                                aes(month(datetime, label=TRUE, abbr=TRUE),
                                power.release, group=factor(year(datetime)), colour=factor(year(datetime))))+
                                geom_smooth()+
                                theme_classic()+
                                labs(x="Month", colour="Year")+
                                ggtitle("Power Release")
plot_power_release
```



```{r}
plot_elevation_By_Month <- ggplot(data=dat %>% filter(dat$datetime >= as.Date("1980-01-01")),
                                aes(month(datetime, label=TRUE, abbr=TRUE),
                                pool.elevation, group=factor(year(datetime)), colour=factor(year(datetime))))+
                                geom_smooth()+
                                theme_classic()+
                                labs(x="Month", colour="Year")+
                                ggtitle("Total Pool Elevation")
                                
plot_elevation_By_Month
```
```{r}
plot_evap<- ggplot(data=dat %>% filter(dat$datetime >= as.Date("1980-01-01")),
                                aes(month(datetime, label=TRUE, abbr=TRUE),
                                evaporation, group=factor(year(datetime)), colour=factor(year(datetime))))+
                                geom_smooth()+
                                theme_classic()+
                                labs(x="Month", colour="Year")+
                                ggtitle("Total Pool Evaporation")
                                
plot_evap
```


# Box Plot Monthly Inflows

```{r}
ggplot(dat)+geom_boxplot(aes(y=total.inflows,
                             fill=format(dat$datetime, '%m')))+
                             xlab("Month")+
                             guides(fill=guide_legend(title="Month"))+
                             theme_bw() + ggtitle("Box Plot of Monthly Inflows")


```

# Box Plot for Monlthy Release
```{r}
ggplot(dat)+geom_boxplot(aes(y=total.release,
                             fill=format(dat$datetime, '%m')))+
                             xlab("Month")+
                             guides(fill=guide_legend(title="Month"))+
                             theme_bw() + ggtitle("Box Plot of Monthly Release")
```

# Box Plot evaporation
```{r}
ggplot(dat)+geom_boxplot(aes(y=evaporation,
                             fill=format(dat$datetime, '%m')))+
                             xlab("Month")+
                             guides(fill=guide_legend(title="Month"))+
                             theme_bw() + ggtitle("Box Plot of Monthly Evaporation")
```
# Power Release


# Box Plot Power Release
```{r}
ggplot(dat)+geom_boxplot(aes(y=power.release,
                             fill=format(dat$datetime, '%m')))+
                             xlab("Month")+
                             guides(fill=guide_legend(title="Month"))+
                             theme_bw() + ggtitle("Box Plot of Monthly Power Release")

```

# Box Plot Total Pool Elevation
```{r}
ggplot(dat)+geom_boxplot(aes(y=pool.elevation,
                             fill=format(dat$datetime, '%m')))+
                             xlab("Month")+
                             guides(fill=guide_legend(title="Month"))+
                             theme_bw() + ggtitle("Box Plot of Pool Elevation")
```

