---
title: "Stats_Project_1"
author: "Duncan Ferguson"
date: "5/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
library(HistData)
```



# Importing File
```{r}
dat<- read.csv("Lake_Powel_Inflow_Elevation_Outflow.csv")
dat

newdat <- aggregate(dat[, 2:4], list(dat$Year), mean)

ts.plot(newdat$total.inflows)
ts.plot(newdat$total.release)
ts.plot(newdat$pool.elevation)

```

```{r}
dat
dat$netflows <- dat$total.inflows - dat$total.release
dat



```

# Testing Anova Tests

```{r}
one.way <- aov(total.inflows ~ total.release, data=dat)
summary(one.way)

```

# Oneway
```{r}
one.way_pool <- aov(pool.elevation ~ total.release, data=dat)
summary(one.way_pool)
```


```{r}
?aov

```








# Testing Flow

```{r}
dat 
dat<-dat[dat$Year >1980]


ggscatter(dat, x = "datetime", y = "pool.elevation",
          add = "reg.line", conf.int=TRUE,
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "datetime", ylab = "pool.elevation")
res4 <- cor.test(dat$Year, dat$netflows, meother = "pearsons") + geom_smooth()
res4



```




